BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Create.cshtml.cs
using BlueBirdSnowboardingApp.models;
using BlueBirdSnowboardingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlueBirdSnowboardingApp.Pages
{
	public class CreateModel : PageModel
    {
        public SelectList MarcaOptionItems { get; set; }

        private ISnowboardService _service;

        public CreateModel(ISnowboardService service)
        {
            _service = service;
        }
        public void OnGet()
        {
            MarcaOptionItems = new SelectList(_service.ObterTodasMarcas(),
                                              nameof(Marca.MarcaId),
                                              nameof(Marca.Descricao));
        }

        

            [BindProperty]
        public Snowboard Snowboard { get; set; }

        public IActionResult OnPost()


        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            //inclusao

            _service.Inlcuir(Snowboard);

            return RedirectToPage("/Index");

        }
    }
}

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Details.cshtml.cs
using BlueBirdSnowboardingApp.models;
using BlueBirdSnowboardingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlueBirdSnowboardingApp.Pages
{
	public class DetailsModel : PageModel
    {
        private ISnowboardService _service;

        public DetailsModel(ISnowboardService service)
        {
            _service = service;
        }

        public Snowboard Snowboard { get; private set; }

        public IActionResult OnGet(int id)
        {
            //var service = new SnowboardService();
            Snowboard = _service.Obter(id);

            if(Snowboard == null)
            {
                return NotFound();
            }

            return Page();

        }
    }
}

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Edit.cshtml.cs
using BlueBirdSnowboardingApp.models;
using BlueBirdSnowboardingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;

namespace BlueBirdSnowboardingApp.Pages
{
	public class EditModel : PageModel
    {
        public SelectList MarcaOptionItems { get; set; }
        private ISnowboardService _service;
        private IToastNotification _toastNotification;
        private readonly IToastNotification toastNotification;

        public EditModel(ISnowboardService service, IToastNotification toastNotification)
        {
            _service = service;
            _toastNotification = toastNotification;
        }

       
       


        [BindProperty]
        public Snowboard Snowboard { get; set; }
       

        public IActionResult OnGet(int id)
        {
            //var service = new SnowboardService();
            Snowboard = _service.Obter(id);
            MarcaOptionItems = new SelectList(_service.ObterTodasMarcas(),
                                             nameof(Marca.MarcaId),
                                             nameof(Marca.Descricao));

            if (Snowboard == null)
            {
                return NotFound();
            }

            return Page();     

        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var snowboardExistente = _service.Obter(Snowboard.Snowboardid);
            if (snowboardExistente == null)
            {
                // Tratar caso em que o snowboard não é encontrado
                // Pode redirecionar para uma página de erro ou mostrar uma mensagem
                _toastNotification.AddErrorToastMessage("Snowboard não encontrado.");
                return Page();
            }

            _service.Alterar(Snowboard);

            _toastNotification.AddSuccessToastMessage("Snowboard alterado com sucesso!");
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostExclusao()

        {
            //Exclusao
            _service.Excluir(Snowboard.Snowboardid);
            _toastNotification.AddSuccessToastMessage("Snowboard Excluido com Suceso");
            return RedirectToPage("/Index");
        }
    }
}

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlueBirdSnowboardingApp.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Index.cshtml.cs
using BlueBirdSnowboardingApp.models;
using BlueBirdSnowboardingApp.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace BlueBirdSnowboardingApp.Pages;

public class IndexModel : PageModel

{
    private ISnowboardService _service;

    public IndexModel(ISnowboardService service)
    {
        _service = service;
    }
    public IList<Snowboard> ListaSnowboards { get; private set; }
    

    public void OnGet()
    {




       // var service = new SnowboardService();

        ListaSnowboards = _service.ObterTodos();

    }
    
    
}

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/AboutUs.cshtml
@page
    <div class="styling flex-container">
        <div class="image-container">
            <img src="~/images/snowboardinglogo.jpg" alt="Blue Bird Snowboarding" class="about-image">
        </div>
        <div class="styling">
            <h1>About Us</h1>
            <p>Welcome to <strong>Blue Bird Snowboarding</strong>, the ultimate destination for snowboarding enthusiasts!</p>
            <p>Founded in <span>[Year of Establishment]</span>, our passion for snowboarding has driven us to curate a collection of the finest snowboarding gear, apparel, and accessories. At Blue Bird Snowboarding, we celebrate the spirit of the mountains, the thrill of the descent, and the camaraderie of the snowboarding community.</p>

            <h2>Our Mission</h2>
            <p>At Blue Bird Snowboarding, we believe that snowboarding is more than just a sport—it's a way of life. Our mission is to inspire and empower riders of all levels to reach new heights, break boundaries, and experience the unparalleled joy of the ride. Here's how we make this happen:</p>
            <ul>
                <li><strong>Premium Quality Products</strong>: Our team handpicks the best products from top brands, ensuring you get the perfect blend of durability, performance, and style.</li>
                <li><strong>Expert Advice</strong>: With years of experience on and off the slopes, our knowledgeable staff is here to guide you, ensuring you make informed choices that suit your unique needs.</li>
                <li><strong>Community Engagement</strong>: We are proud members of the snowboarding community. By hosting events, workshops, and partnering with local organizations, we aim to cultivate and elevate the sport we all love.</li>
            </ul>

            <h2>Why Choose Blue Bird Snowboarding?</h2>
            <ol>
                <li><strong>Vast Selection</strong>: From boards to bindings, helmets to heated gloves, we've got you covered. Our diverse range ensures you find exactly what you need.</li>
                <li><strong>Unparalleled Customer Service</strong>: Your satisfaction is our priority. We're dedicated to ensuring you have a smooth shopping experience, from browsing to boarding.</li>
                <li><strong>Passion for the Sport</strong>: We live and breathe snowboarding. Our love for the sport translates into everything we do, making us more than just a store—we're a community.</li>
            </ol>

            <p>Join us on this exciting journey down the slopes, and let Blue Bird Snowboarding be your trusted partner in all your snowboarding adventures!</p>
        </div>


    </div>

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Create.cshtml
@page
@model BlueBirdSnowboardingApp.Pages.CreateModel
<div class="row pt-5">
    <div class="col-md-4">
        <form method="post">
            <h4>Inclusão de Snowboarding</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Snowboard.Nome" class="control-label"></label>
                <input asp-for="Snowboard.Nome" class="form-control" />
                <span asp-validation-for="Snowboard.Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.Descricao" class="control-label"></label>
                <input asp-for="Snowboard.Descricao" class="form-control" />
                <span asp-validation-for="Snowboard.Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.ImagemUri" class="control-label"></label>
                <input asp-for="Snowboard.ImagemUri" class="form-control" />
                <span asp-validation-for="Snowboard.ImagemUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.Preco" class="control-label"></label>
                <input asp-for="Snowboard.Preco" class="form-control" />
                <span asp-validation-for="Snowboard.Preco" class="text-danger"></span>
            </div>



            <div class="form-group mt-3 mb-3">
                <input class="form-check-input" asp-for="Snowboard.EntregaExpressa" />
                <label asp-for="Snowboard.EntregaExpressa"></label>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.DataCadastro" class="control-label"></label>
                <input asp-for="Snowboard.DataCadastro" class="form-control" />
                <span asp-validation-for="Snowboard.DataCadastro" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 mb-3">
                <label asp-for="Snowboard.MarcaId" class="control-label"></label>
                <select class="form-select" asp-for="Snowboard.MarcaId"
                        asp-items="Model.MarcaOptionItems">
                    <option value="">Selecione uma opção</option>
                </select>
                <span asp-validation-for="Snowboard.MarcaId" class="text-danger">
                </span>
            </div>





            <div class="form-group mt-4">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts{

               @{
                   await Html.RenderPartialAsync("_ValidationScriptsPartial");
               } 

                }

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Details.cshtml
@page "/Snowboard/{slug}/{id}"
@model BlueBirdSnowboardingApp.Pages.DetailsModel

    <h2 class="my-3">@Model.Snowboard.Nome</h2>
    <div class="row">
        <div class="col-4">
            <img class="img-fluid rounded" src="@Model.Snowboard.ImagemUri">
        </div>
        <div class="col-6">
            <h4 class="my-3">Sobre:</h4>
            <p>@Model.Snowboard.Descricao</p>
            <h4 class="my-3">Mais Info:</h4>
            <ul>

                <li>
                <label asp-for="Snowboard.Preco"></label>
                : @Html.DisplayFor(model => model.Snowboard.Preco)</li>
                <li>
                <label asp-for="Snowboard.EntregaExpressa"></label>
                : @Html.DisplayFor(model => model.Snowboard.EntregaExpressa)</li>
                <li>
                Availible since: @Html.DisplayFor(model => model.Snowboard.DataCadastro)</li>
            </ul>
            <a class="btn my-3 btn-primary"
               asp-page="/Edit" asp-route-id="@Model.Snowboard.Snowboardid">Editar</a>
        </div>
    </div>

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Edit.cshtml
@page
@model BlueBirdSnowboardingApp.Pages.EditModel

<div class="row pt-5">
    <div class="col-md-4">
        <form method="post">
            <h4>Alteracão de Snowboarding</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Snowboard.Snowboardid" />

            <div class="form-group">
                <label asp-for="Snowboard.Nome" class="control-label"></label>
                <input asp-for="Snowboard.Nome" class="form-control" />
                <span asp-validation-for="Snowboard.Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.Descricao" class="control-label"></label>
                <input asp-for="Snowboard.Descricao" class="form-control" />
                <span asp-validation-for="Snowboard.Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.ImagemUri" class="control-label"></label>
                <input asp-for="Snowboard.ImagemUri" class="form-control" />
                <span asp-validation-for="Snowboard.ImagemUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.Preco" class="control-label"></label>
                <input asp-for="Snowboard.Preco" class="form-control" />
                <span asp-validation-for="Snowboard.Preco" class="text-danger"></span>
            </div>



            <div class="form-group mt-3 mb-3">
                <input class="form-check-input" asp-for="Snowboard.EntregaExpressa" />
                <label asp-for="Snowboard.EntregaExpressa"></label>
            </div>

            <div class="form-group">
                <label asp-for="Snowboard.DataCadastro" class="control-label"></label>
                <input asp-for="Snowboard.DataCadastro" class="form-control" />
                <span asp-validation-for="Snowboard.DataCadastro" class="text-danger"></span>
            </div>
            <div class="form-group mt-3 mb-3">
                <label asp-for="Snowboard.MarcaId" class="control-label"></label>
                <select class="form-select" asp-for="Snowboard.MarcaId"
                        asp-items="Model.MarcaOptionItems">
                    <option value="">Selecione uma opção</option>
                </select>
                <span asp-validation-for="Snowboard.MarcaId" class="text-danger">
                </span>
            </div>


            <div class="form-group mt-4">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <input type="submit" value="Excluir" class="btn btn-danger"
                       asp-page-handler="Exclusao" />
            </div>
        </form>
    </div>
</div>

@section Scripts{

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="row justify-content-md-center">

    @foreach (var item in Model.ListaSnowboards)
    {
        <div class="card col-3 m-3">
            <img src="@item.ImagemUri" class="p-3" style="border-radius: 25px">
            <div class="card-body">
                <h5 class="card-title">@item.Nome</h5>
                <p class="card-text">@item.Descricao</p>
                <a class="btn btn-primary"
                   asp-page="/Details"
                   asp-route-slug="@item.Nome"
                   asp-route-id="@item.Snowboardid">Ver mais</a>
            </div>
        </div>
    }

    
</div>

BlueBirdSnowboardingApp/BlueBirdSnowboardingApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlueBirdSnowboardingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true">
    <link rel="stylesheet" href="~/BlueBirdSnowboardingApp.styles.css" asp-append-version="true" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-page="/Index">Blue Bird Snowboarding</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-page="/Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-page="/Privacy">Privacy</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-page="/AboutUs">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-page="/Create">Include</a>
                        </li>


                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlueBirdSnowboardingApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

   
</body>
</html>